### PR TITLE
delete function working for records page

### PR DESCRIPTION
**Pull request by paulbryandy**
This change is [Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/27)

### CODE REVIEW

**Review by snretuerma — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/27)* status: all files reviewed, 3 unresolved discussions (waiting on @paulbryandy)

___
*[app/Http/Controllers/UserController.php, line 425 at r1](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/27#-MLMSujm1vy6GDfEQ5m4:-MLMSujnC605oBt0GenI:b-l6mwxj) ([raw file](https://github.com/snretuerma/sorphilhealthsystem/blob/afc3a772d0dd31098aec4936b27cdb2ebc17a5a5/app/Http/Controllers/UserController.php#L425)):*
> ```PHP
> 
>         // }
>         // dd(sizeof($request->item['contributions'])-1);
> ```

remove
___
*[app/Http/Controllers/UserController.php, line 426 at r1](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/27#-MLMSw8W5ivhiDJs7bRo:-MLMSw8W5ivhiDJs7bRp:b29ct5q) ([raw file](https://github.com/snretuerma/sorphilhealthsystem/blob/afc3a772d0dd31098aec4936b27cdb2ebc17a5a5/app/Http/Controllers/UserController.php#L426)):*
> ```PHP
>         // }
>         // dd(sizeof($request->item['contributions'])-1);
>         $i = (sizeof($request->item['contributions'])-1) ;
> ```

spacing
___
*[app/Http/Controllers/UserController.php, line 439 at r1](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/27#-MLMSzMs0cDL-FTxNpGv:-MLMSzMs0cDL-FTxNpGw:b29ct5q) ([raw file](https://github.com/snretuerma/sorphilhealthsystem/blob/afc3a772d0dd31098aec4936b27cdb2ebc17a5a5/app/Http/Controllers/UserController.php#L439)):*
> ```PHP
>     {
>         // dd($req);
>         for($i=0;$i<sizeof($req->data);$i++) {
> ```

spacing

**Review by snretuerma — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/27)* status: all files reviewed, 4 unresolved discussions (waiting on @paulbryandy)

___
*[app/Http/Controllers/UserController.php, line 434 at r2](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/27#-MLMUXXPE4B-h_EYChE5:-MLMUXXPE4B-h_EYChE6:bg8ur90) ([raw file](https://github.com/snretuerma/sorphilhealthsystem/blob/de9980d25a9e7f2e89ee2d01d6ac008909ecc554/app/Http/Controllers/UserController.php#L434)):*
> ```PHP
>     public function deleteContribution(Request $req)
>     {
>         for($i=0;$i<sizeof($req->data);$i++) {
> ```

for ($i=0; $i<sizeof ($req->data); $i++) {
___
*[resources/js/components/user/PersonnelComponent.vue, line 955 at r2](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/27#-MLMUcx2Ds1YEdXDb6zp:-MLMUcx38wD8yx5Ilbli:ba7nx8w) ([raw file](https://github.com/snretuerma/sorphilhealthsystem/blob/de9980d25a9e7f2e89ee2d01d6ac008909ecc554/resources/js/components/user/PersonnelComponent.vue#L955)):*
> ```Vue
>                     var _this = this;
>                     axios
>                         .post("personnel_delete/" + id)
> ```

.post(`personnel_delete/${id}`)

**Review by snretuerma — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/27)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by paulbryandy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/27#-:-MLMakuF0OQU3_yYwPzS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by paulbryandy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/27#-:-MLMamyr9yrG3JlrJ0pw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by snretuerma — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/27#-:-MLMbGZ3AvP08tYOrk22:bg7igk9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
