### PR TITLE
Summary by batch

### PR DESCRIPTION
**Pull request by paulbryandy**
This change is [Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52)

### CODE REVIEW

**Review by paulbryandy — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52#-:-MOZ-q_l43sa5HLB0w3u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kennael22 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @paulbryandy)

**Review by snretuerma — CHANGES_REQUESTED** [review]
Will check this tomorrow

> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52#-:-MO_VKpZDsHL7CDsHxnt:bcle1vq)* status: all files reviewed, 4 unresolved discussions (waiting on @paulbryandy)

___
*[resources/js/components/user/RecordChild.vue, line 771 at r1](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52#-MO_Ud835oO9XwBiWam-:-MO_Ud835oO9XwBiWam0:bvj60qu) ([raw file](https://github.com/snretuerma/sorphilhealthsystem/blob/fbf2ae1c33d7ad4fae7112c6f4c64823fb99b1a5/resources/js/components/user/RecordChild.vue#L771)):*
> ```Vue
>                                             id: 'wsc' + (Math.random().toString(36).substring(7)) + (i + 1),
>                                             value: '',
>                                             message: "This cell must contain 'NULL' or Physician Name, format(LastName, FirstName MiddleName).If you need to add more physician, a delimeter comma ',' is required. ",
> ```

"This cell must contain 'NULL' or Physician Name, format(LastName, FirstName MiddleName). If you need to add more physician, a comma delimeter ',' is required. "
___
*[resources/js/components/user/RecordChild.vue, line 828 at r1](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52#-MO_Ub1E4JlttSda_ymD:-MO_Ub1E4JlttSda_ymE:b-3bcg04) ([raw file](https://github.com/snretuerma/sorphilhealthsystem/blob/fbf2ae1c33d7ad4fae7112c6f4c64823fb99b1a5/resources/js/components/user/RecordChild.vue#L828)):*
> ```Vue
>                                                     id: 'wsc' + (Math.random().toString(36).substring(7)) + (i + 1),
>                                                     value: cell.v,
>                                                     message: "must contain 'NULL' or Physician Name, format(LastName, FirstName MiddleName). If you need to add more physician, a delimeter comma ',' is required.",
> ```

"must contain 'NULL' or Physician Name, format(LastName, FirstName MiddleName). If you need to add more physician, a comma delimeter ',' is required."
___
*[resources/js/components/user/RecordChild.vue, line 837 at r1](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52#-MO_UMP25ibQe3DdK_18:-MO_UMP25ibQe3DdK_19:b-3bcg04) ([raw file](https://github.com/snretuerma/sorphilhealthsystem/blob/fbf2ae1c33d7ad4fae7112c6f4c64823fb99b1a5/resources/js/components/user/RecordChild.vue#L837)):*
> ```Vue
>                                                     id: 'wsc' + (Math.random().toString(36).substring(7)) + (i + 1),
>                                                     value: cell.v,
>                                                     message: "must contain 'NULL' or Physician Name, format(LastName, FirstName MiddleName). If you need to add more physician, a delimeter comma ',' is required.",
> ```

"must contain 'NULL' or Physician Name, format(LastName, FirstName MiddleName). If you need to add more physician, a comma delimeter ',' is required."
___
*[resources/js/components/user/SummaryComponent.vue, line 356 at r1](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52#-MO_UvILEcGt0VNj3nyz:-MO_UvIMAtrVWHEEGjMe:b5uj72w) ([raw file](https://github.com/snretuerma/sorphilhealthsystem/blob/fbf2ae1c33d7ad4fae7112c6f4c64823fb99b1a5/resources/js/components/user/SummaryComponent.vue#L356)):*
> ```Vue
>                     this.getSummary(response.data[0].batch);
>                 })
>                 .catch(function(error) {});
> ```

            |axios
            |"NOT TAB HERE" .get("get_batch")
            |.then(response => {
            4 spaces|response.data.push({ batch: "All" });
                    this.batch = response.data;
                    this.value[0] = response.data[0].batch;
                    this.first_batch = response.data[0].batch;
                    this.getSummary(response.data[0].batch);
            |})

**Review by kennael22 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @kennael22 and @paulbryandy)

**Review by snretuerma — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52)* status: all files reviewed, 1 unresolved discussion (waiting on @paulbryandy)

**Review by snretuerma — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52)* status: all files reviewed, 1 unresolved discussion (waiting on @paulbryandy)

**Review by snretuerma — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52#-:-MOeEaUzEeAqI-g3PSvU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @paulbryandy)

**Review by snretuerma — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/52)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
