### PR TITLE
Find and fix bug

### PR DESCRIPTION
**Pull request by paulbryandy**
This change is [Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/24)

### CODE REVIEW

**Review by snretuerma — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/24)* status: all files reviewed, 3 unresolved discussions (waiting on @paulbryandy)

___
*[resources/js/components/admin/PatientComponent.vue, line 1005 at r1](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/24#-MLL22byCEU3Gz6fj0CB:-MLL22bz1W3gVr1uV0Ox:b5r95c8) ([raw file](https://github.com/snretuerma/sorphilhealthsystem/blob/2441632d1fb478c1eed8b147b0ee6cd9d27e0ab8/resources/js/components/admin/PatientComponent.vue#L1005)):*
> ```
>                         if (this.form.name_suffix == null) {
>                             this.form.name_suffix = "";
> ```

trim white spaces before saving
___
*[resources/js/components/admin/PersonnelComponent.vue, line 943 at r1](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/24#-MLL29kzB6PHO-h398mZ:-MLL29kzB6PHO-h398m_:bnj7hl0) ([raw file](https://github.com/snretuerma/sorphilhealthsystem/blob/2441632d1fb478c1eed8b147b0ee6cd9d27e0ab8/resources/js/components/admin/PersonnelComponent.vue#L943)):*
> ```Vue
>                         }
>                         if (this.form.name_suffix == null) {
>                             this.form.name_suffix = "";
> ```

same as above
___
*[resources/js/components/user/RestoreComponent.vue, line 300 at r1](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/24#-MLL2JYBBBxYxVgpN9RR:-MLL2JYC3eCmZDkrcn2o:bmbrefo) ([raw file](https://github.com/snretuerma/sorphilhealthsystem/blob/2441632d1fb478c1eed8b147b0ee6cd9d27e0ab8/resources/js/components/user/RestoreComponent.vue#L300)):*
> ```Vue
>                     });
>                     this.data = response.data;
>                     console.log(this.data);
> ```

remove if not necessary

**Review by snretuerma — COMMENTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/24)* status: all files reviewed, 3 unresolved discussions (waiting on @paulbryandy)

**Review by snretuerma — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/24)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by paulbryandy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/24#-:-MLL6t_Z1AddjEWg0oeY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by snretuerma — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/24)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by snretuerma — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/24#-:-MLL71Tp3oIS5sZDF5Zj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
