### PR TITLE
Find and fix bug

### PR DESCRIPTION
**Pull request by paulbryandy**
This change is [Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/23)

### CODE REVIEW

**Review by snretuerma — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/23)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by paulbryandy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/23#-:-MLBueV1BlVSHGTuQuIq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by snretuerma — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/23)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by snretuerma — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/23#-:-MLBvCEM9Pe_DBVjKvcq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kennael22 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/snretuerma/sorphilhealthsystem/23#-:-MLBvVMrCOD3c_r1UvAs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
